---
dist: bionic
sudo: required

language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip3 install ansible-lint==4.2.0 yamllint==1.21.0
  - ansible-lint --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
