---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true

- name: restart application
  systemd:
    name: application
    state: restarted
    enabled: true
    daemon_reload: true
