---
## Check if security upgrade works:
##
## unattended-upgrades --dry-run --debug
## cat /var/log/unattended-upgrades/unattended-upgrades.log

- name: Install packages
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: true
    force_apt_get: true

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Enable unattended-upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: present
    line: '{{ item }}'
  loop:
    - 'APT::Periodic::Enable "1";'
    - 'APT::Periodic::Update-Package-Lists "1";'
    - 'APT::Periodic::Download-Upgradeable-Packages "1";'
    - 'APT::Periodic::AutocleanInterval "3";'
    - 'APT::Periodic::Unattended-Upgrade "1";'

- name: Create /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
